### ISSUE TITLE
bsvarSIGNs v1.0 CRAN submission plan

### ISSUE THREAD

**Issue by donotdespair** [bsvars/bsvarSIGNs#14]
## Todos agreed on in conversation on 2024-06-11

- [x] finalise **cpp** code for GLP model #13 
- [x] NOT DOING THIS! prepare a separate `specify_*` function and `estimate` method for the particular models by #13
- [x] import generics from **bsvars** #21 and write **bsvarSIGNs**-specific methods:
  - [x] `estimate`
  - [x] #25 
  - [x] `forecast` including conditional forecast #23 
  - [x] correct `forecast` once #27 is done

## Final round-up

- [x] documentation
- [x] tests
- [x] NEWS file
- [x] DONE BY THE PACKAGE NO NEED TO DO ANYTHING: CITATION file
- [x] data reproduction files
- [x] logo
- [x] **pkgdown** website
- [x] final checks
