### ISSUE TITLE
vignette's out!

### ISSUE THREAD

**Issue by donotdespair** [bsvars/bsvarSIGNs#53]
## todos 

- [x] update the vignette [bsvars/bsvarSIGNs_vignette](https://github.com/bsvars/bsvarSIGNs_vignette)
  - [x] grammar
  - [x] final polishing
- [x] publish as arxiv
  - [x] prepare the submission
  - [x] submit 
  - [x] wait for the DOI and publication
- [ ] update the package
  - [x] put in DESCRIPTION: `VignetteBuilder: knitr`
  - [x] create forlder `vignettes` and `vignettes/pdf`
  - [x] copy formatted pdf file with the vignette
  - [x] create the `vignettes/bsvarSIGNs_vignette.Rnw` file
  - [x] update CITATION
  - [x] change package description in DESCRIPTION
  - [x] update `README.Rmd` and compile
  - [x] update NEWS
  - [x] update `.github/workflows/R-CMD-check.yaml`
  - [x] perform checks
- [ ] the submission issue
